46 response streaming
jathonderulo/SwEngGroup27 pull request #60
Opened 2024-03-27 17:47 UTC by HughFinnegan

2024-03-28 14:23 UTC, TheAvailer requested changes
Small change on final lines of Backend/index.js necessary for keeping the CI/CD pipeline working (I believe I left a review comment on the specific lines, contact me if you can't find it).
Everything else changed within backend looks good to me.

2024-03-28 14:23 UTC, TheAvailer commented on Backend/index.js
>  });
@wardr3 Slightly modify this line to what it's like within main and backend's index.js (assigning app.listen(.....); ) to a const 'server', as that's used within the CI/CD, leaving it out would cause an issue later that would need another commit.

2024-03-28 22:17 UTC, wardr3 commented on Backend/index.js
>  });
Should be correct now

2024-03-28 23:03 UTC, wardr3 commented
## Don't merge this yet
This branch has weird issues with sending messages to the backend that only occur after a few consecutive questions. Don't merge it until I update this comment.

2024-03-29 14:07 UTC, TheAvailer approved these changes

2024-03-29 14:15 UTC, TheAvailer requested changes
Resolve issue #62

2024-03-29 18:34 UTC, HughFinnegan commented
Response bug fixed. The "handleMessageSubmit" is no longer asynchronous to fit in with streaming. Res.send() is returned as soon as the message is received by backend to ensure the post request isn't pending indefinitely (which was causing the bug) but streaming still works because we don't use handleMessageSubmit to intepret any response and is instead run through SSE.

2024-04-02 02:25 UTC, TheAvailer approved these changes

2024-04-02 02:38 UTC, merged